version: '3.9'

services:
  db:
    image: mysql:8
    container_name: mysql_gestion
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: incident_management
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ssword
    #ports:
    #  - "3308:3306"   # Opcional, solo si quieres acceder desde fuera de Docker
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer_mysql
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
    networks:
      - backend

  app:
    build: .
    container_name: gestion_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/incident_management?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: p@ssword
    ports:
      - "8082:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
